// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiPMU.Models;

public class Cheval
{
    public string NumGeny { get; set; }

    public short NumCourse { get; set; }

    public short Numero { get; set; }

    public string Nom { get; set; }

    public string Corde { get; set; }

    public string SexAge { get; set; }

    public float DistPoid { get; set; }

    public string Deferre { get; set; }

    public string Jokey { get; set; }

    public string Entraineur { get; set; }

    public int? Gains { get; set; }

    public string ZoneABC { get; set; }

    public short? ClaZone { get; set; }

    public float? Cote11h { get; set; }

    public float? CoteDef { get; set; }

    public float? CoteGen { get; set; }

    public float? Pourcent11h { get; set; }

    public float? PourcentDef { get; set; }

    public short? PlaceArrivee { get; set; }

    public float? ClasCoefReussite { get; set; }

    public float? CoefReussite { get; set; }

    public float? IndFor { get; set; }

    public float? IndForme { get; set; }

    public int? NbCourses { get; set; }

    public int? NbVictoires { get; set; }

    public int? NbPlaces { get; set; }

    public int? ClaCote { get; set; }

    public float? PtsOR { get; set; }

    public int? ClaOR { get; set; }

    public int? PtsAR { get; set; }

    public int? ClaAR { get; set; }

    public float? PtsCX { get; set; }

    public int? ClaCX { get; set; }

    public int? PtsCRIFX { get; set; }

    public int? ClaCRIFX { get; set; }

    public int? PtsTMatic { get; set; }

    public int? ClaTMatic { get; set; }

    public int? PtsHisto { get; set; }

    public int? ClaHisto { get; set; }

    public int? PtsRub { get; set; }

    public int? ClaRub { get; set; }

    public float? PrcCh { get; set; }

    public int? PrcDr { get; set; }

    public int? PrcEn { get; set; }

    public int? NbBloc { get; set; }

    public int? NbCouples { get; set; }

    public float? VaCouples { get; set; }

    public string Median { get; set; }

    public int? ClasMN { get; set; }

    public int? ClasPT { get; set; }

    public int? ClasRE { get; set; }

    public int? ClasRD { get; set; }

    public int? ClaIDC { get; set; }

    public int? ClaCFP { get; set; }

    public int? PtsMN { get; set; }

    public int? PtsPT { get; set; }

    public int? PtsRD { get; set; }

    public int? PtsRE { get; set; }

    public float? PtsCFP { get; set; }

    public float? PtsIDC { get; set; }

    public int? ClasPtsStats { get; set; }

    public float PtsStats { get; set; }

    public int? ClasValStats { get; set; }

    public int? ValStats { get; set; }

    public int? ClasStats { get; set; }

    public float CumStats { get; set; }

    public int? PtsSynth { get; set; }

    public int? ClasSynth { get; set; }

    public DateTime? RecordDate { get; set; }

    public int? RecordPlace { get; set; }

    public int? RecordDistance { get; set; }

    public string RecordFerrage { get; set; }

    public string Record { get; set; }

    public string Avis { get; set; }

    public int? ClasHMP { get; set; }

    public int? PtsED { get; set; }

    public int? ClasED { get; set; }

    public int? PtsR10 { get; set; }

    public int? ClasR10 { get; set; }

    public int? PtsRC { get; set; }

    public int? ClasRC { get; set; }

    public int? JA { get; set; }

    public string Musique { get; set; }

    public DateTime? DateModif { get; set; }
}