// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiPMU.Models;

public partial class Cheval
{
    public string NumGeny { get; set; }

    public short NumCourse { get; set; }

    public short Numero { get; set; }

    public string Nom { get; set; }

    public string Corde { get; set; }

    public string SexAge { get; set; }

    public float DistPoid { get; set; }

    public string Deferre { get; set; }

    public string Jokey { get; set; }

    public string Entraineur { get; set; }

    public int? Gains { get; set; }

    public string ZoneAbc { get; set; }

    public short? ClaZone { get; set; }

    public float? Cote11h { get; set; }

    public float? CoteDef { get; set; }

    public float? CoteGen { get; set; }

    public float? Pourcent11h { get; set; }

    public float? PourcentDef { get; set; }

    public short? PlaceArrivee { get; set; }

    public double? ClasCoefReussite { get; set; }

    public float? CoefReussite { get; set; }

    public float? IndFor { get; set; }

    public double? IndForme { get; set; }

    public int? NbCourses { get; set; }

    public int? NbVictoires { get; set; }

    public int? NbPlaces { get; set; }

    public int? ClaCote { get; set; }

    public float? PtsOr { get; set; }

    public int? ClaOr { get; set; }

    public int? PtsAr { get; set; }

    public int? ClaAr { get; set; }

    public float? PtsCx { get; set; }

    public int? ClaCx { get; set; }

    public int? PtsCrifx { get; set; }

    public int? ClaCrifx { get; set; }

    public int? PtsTmatic { get; set; }

    public int? ClaTmatic { get; set; }

    public int? PtsHisto { get; set; }

    public int? ClaHisto { get; set; }

    public int? PtsRub { get; set; }

    public int? ClaRub { get; set; }

    public float? PrcCh { get; set; }

    public int? PrcDr { get; set; }

    public int? PrcEn { get; set; }

    public int? NbBloc { get; set; }

    public int? NbCouples { get; set; }

    public float? VaCouples { get; set; }

    public string Median { get; set; }

    public int? ClasMn { get; set; }

    public int? ClasPt { get; set; }

    public int? ClasRe { get; set; }

    public int? ClasRd { get; set; }

    public int? ClaIdc { get; set; }

    public int? ClaCfp { get; set; }

    public int? PtsMn { get; set; }

    public int? PtsPt { get; set; }

    public int? PtsRd { get; set; }

    public int? PtsRe { get; set; }

    public float? PtsCfp { get; set; }

    public float? PtsIdc { get; set; }

    public int? ClasPtsStats { get; set; }

    public float PtsStats { get; set; }

    public int? ClasValStats { get; set; }

    public int? ValStats { get; set; }

    public int? ClasStats { get; set; }

    public float CumStats { get; set; }

    public int? PtsSynth { get; set; }

    public int? ClasSynth { get; set; }

    public DateTime? RecordDate { get; set; }

    public int? RecordPlace { get; set; }

    public int? RecordDistance { get; set; }

    public string RecordFerrage { get; set; }

    public string Record { get; set; }

    public string Avis { get; set; }

    public DateTime? DateModif { get; set; }

    public int? ClasHmp { get; set; }

    public int? PtsEd { get; set; }

    public int? ClasEd { get; set; }

    public int? PtsR10 { get; set; }

    public int? ClasR10 { get; set; }

    public int? PtsRc { get; set; }

    public int? ClasRc { get; set; }

    public int? Ja { get; set; }

    public string Musique { get; set; }
}