// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiPMU.Models;

public partial class Course
{
    public string NumGeny { get; set; }

    public short NumCourse { get; set; }

    public string Discipline { get; set; }

    public float? Difficulte { get; set; }

    public bool? Jcouples { get; set; }

    public bool? Jtrio { get; set; }

    public bool? Jmulti { get; set; }

    public bool? Jquinte { get; set; }

    public bool? Autostart { get; set; }

    public string TypeCourse { get; set; }

    public string Cordage { get; set; }

    public int? Allocation { get; set; }

    public int? Distance { get; set; }

    public int? Partants { get; set; }

    public string Libelle { get; set; }

    public short? Premier { get; set; }

    public short? Deuxieme { get; set; }

    public short? Troisieme { get; set; }

    public short? Quatrieme { get; set; }

    public short? Cinquieme { get; set; }

    public float? SimpleGagnant { get; set; }

    public float? SimplePlace1 { get; set; }

    public float? SimplePlace2 { get; set; }

    public float? SimplePlace3 { get; set; }

    public float? CoupleGagnant { get; set; }

    public float? CouplePlace12 { get; set; }

    public float? CouplePlace13 { get; set; }

    public float? CouplePlace23 { get; set; }

    public float? Trio { get; set; }

    public float? Sur24 { get; set; }

    public float? TierceO { get; set; }

    public float? TierceD { get; set; }

    public float? QuarteO { get; set; }

    public float? QuarteD { get; set; }

    public float? Quarte3 { get; set; }

    public float? QuinteO { get; set; }

    public float? QuinteD { get; set; }

    public float? Quinte4 { get; set; }

    public float? Quinte45 { get; set; }

    public float? Quinte3 { get; set; }

    public float? Multi4 { get; set; }

    public float? Multi5 { get; set; }

    public float? Multi6 { get; set; }

    public float? Multi7 { get; set; }

    public float? QuadrioO { get; set; }

    public float? QuadrioD { get; set; }

    public float? Quadrio3 { get; set; }

    public float? Quadrio2 { get; set; }

    public int? CptStats { get; set; }

    public DateTime? DateModif { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public short? Age { get; set; }
}