// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiPMU.Models;

public class EntraineurJokey
{
    public string NumGeny { get; set; }

    public string Entjok { get; set; }

    public string Nom { get; set; }

    public int? NbCourses { get; set; }

    public int? NbVictoires { get; set; }

    public int? Ecart { get; set; }

    public short? NbCR { get; set; }

    public DateTime? DateModif { get; set; }
}