// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiPMU.Models;

public class Performance
{
    public string Nom { get; set; }

    public DateTime DatePerf { get; set; }

    public string Lieu { get; set; }

    public float? Dist { get; set; }

    public int? Gains { get; set; }

    public short? Partants { get; set; }

    public string Corde { get; set; }

    public string Cordage { get; set; }

    public string Deferre { get; set; }

    public float? Poid { get; set; }

    public string Discipline { get; set; }

    public string TypeCourse { get; set; }

    public int? Allocation { get; set; }

    public string Place { get; set; }

    public string RedKDist { get; set; }

    public float? Cote { get; set; }

    public string Avis { get; set; }

    public string Video { get; set; }

    public DateTime? DateModif { get; set; }
}