// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiPMU.Models;

public class Reunion
{
    public string NumGeny { get; set; }

    public int? NumReunion { get; set; }

    public string LieuCourse { get; set; }

    public DateTime? DateReunion { get; set; }

    public DateTime? DateModif { get; set; }
}